apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-25mb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0021-tenant/ci10t-786-0021-app/devfile-sample-25mb@sha256:353167a26bc7f1e8b2ccbeb72d65643bc3bf385796787c8dcc91ec1f5f2e261f
        name: my-nodejs
        resources: {}
status: {}
